name: Build


on: [push]

jobs:
  mockbuild:
    runs-on: ubuntu-latest

    container:
      image: 'quay.io/fedora/fedora:rawhide'
      options: '--privileged'

    steps:
      - name: Install fedpkg
        run: dnf -y install fedpkg
      - name: Check out qt6-qtwebengine
        run: fedpkg co -a qt6-qtwebengine
      - name: Build qt6-qtwebengine
        run: fedpkg mockbuild
        working-directory: ./qt6-qtwebengine
